#!/bin/sh

RESOLV="/etc/resolv.conf"
RVBACK="/etc/resolv.conf.bak"
NULL="/dev/null"

ns1="nameserver 178.22.122.100"
ns2="nameserver 185.51.200.2"

nsexist() {
	cat $RESOLV | grep "$1" > $NULL
	return $?
}
isenabled() {
	if nsexist "$ns1" || nsexist "$ns2"; then
		return 0
	else
		return 1
	fi
}

case $1 in
	enable)
		if isenabled; then
			echo "Shecan is already enabled"	
		else	
			cp $RESOLV $RVBACK
			echo "nameserver 178.22.122.100
nameserver 185.51.200.2
`cat $RESOLV`" > $RESOLV	
			echo "Shecan enabled"
		fi
		;;
	disable)
		if isenabled; then
			cp $RVBACK $RESOLV
			echo "Shecan disabled"
		else
			echo "Shecan is not enabled"
		fi
		;;
	*)
		echo "Usage: shecan [enable|disable]"
		;;
esac
